---
title: "migration_circleplot"
author: "Martin Monkman"
date: "July 29, 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Engagement State Migration

This uses the R package `circlize` to create a migration plot showing the volume of change from one engagement state to another between cycles of the WES.


[http://urbandemographics.blogspot.ca/2014/04/circular-migration-flow-plots-in-r.html]

[http://www.global-migration.info/VID%20WP%20Visualising%20Migration%20Flow%20Data%20with%20Circular%20Plots.pdf]

[https://gjabel.wordpress.com/2016/05/18/updated-circular-plots-for-directional-bilateral-migration-data/]

[https://gjabel.wordpress.com/2014/03/28/circular-migration-flow-plots-in-r/]


[https://cran.r-project.org/web/packages/circlize/index.html]

(An introduction to circlize package)[https://cran.r-project.org/web/packages/circlize/vignettes/circlize.pdf]

[https://www.r-bloggers.com/euro-2016-squads-part-deux/]





```{r package}

setwd("C:/@data/GitHub/WorkInProgress")

library(circlize)


```



### Circlize

[Visualize Relations by Chord Diagram](https://cran.r-project.org/web/packages/circlize/vignettes/visualize_relations_by_chord_diagram.pdf)

```{r}

library(circlize)

# create data in matrix format (mat)

set.seed(999)
mat = matrix(sample(18, 18), 3, 6)
rownames(mat) = paste0("S", 1:3)
colnames(mat) = paste0("E", 1:6)
mat

# flip into data frame (df)

df = data.frame(from = rep(rownames(mat), times = ncol(mat)),
to = rep(colnames(mat), each = nrow(mat)),
value = as.vector(mat),
stringsAsFactors = FALSE)
df = df[sample(18, 10), ]
df


# this is all it takes to make a chord diagram

chordDiagram(df)
circos.clear()


# set gap between sectors

circos.par(gap.degree = c(rep(2, length(unique(df[[1]]))-1), 10,
  rep(2, length(unique(df[[2]]))-1), 10))
chordDiagram(df)
circos.clear()


# set start degree

circos.par(start.degree = 90)
chordDiagram(df)
circos.clear()

# set order of segments (manual)

chordDiagram(df, order = c("S1", "E1", "E2", "S2", "E3", "E4", "S3", "E5", "E6"))
circos.clear()


# -----------

# add arrows to the links

circos.link()
chordDiagram(df)
circos.clear()



circos.link(sector.index1, 0, sector.index2, 0)
circos.link(sector.index1, c(0, 1), sector.index2, 0)
circos.link(sector.index1, c(0, 1), sector.index2, c(1, 2))
circos.link(sector.index1, c(0, 1), sector.index2, 0, col, lwd, lty, border)


# ok what is this "sector.index1"? What is the variable to include?

circos.link(sector.index1, 0, sector.index2, 0)
circos.link(sector.index1, c(0, 1), sector.index2, 0)
circos.link(sector.index1, c(0, 1), sector.index2, c(1, 2))
circos.link(sector.index1, c(0, 1), sector.index2, 0, col, lwd, lty, border)



```

### An introduction to circlize package
[PDF of vignette](https://cran.r-project.org/web/packages/circlize/vignettes/circlize.pdf)


```{r}

# An introduction to circlize package
# https://cran.r-project.org/web/packages/circlize/vignettes/circlize.pdf

# create data set
set.seed(999)
n = 1000
a = data.frame(factor = sample(letters[1:8], n, replace = TRUE),
x = rnorm(n), y = runif(n))


# initialize plot
library(circlize)
par(mar = c(1, 1, 1, 1), lwd = 0.1, cex = 0.7)
circos.par("track.height" = 0.1)
circos.initialize(factors = a$factor, x = a$x)

# draw first track (alternating red and green points)
circos.trackPlotRegion(factors = a$factor, y = a$y,
panel.fun = function(x, y) {
circos.axis()
})
col = rep(c("#FF0000", "#00FF00"), 4)
circos.trackPoints(a$factor, a$x, a$y, col = col, pch = 16, cex = 0.5)
circos.text(-1, 0.5, "left", sector.index = "a", track.index = 1)
circos.text(1, 0.5, "right", sector.index = "a")

# draw second track (cirle of histograms inside the first track)
bgcol = rep(c("#EFEFEF", "#CCCCCC"), 4)
circos.trackHist(a$factor, a$x, bg.col = bgcol, col = NA)

# draw third track
circos.trackPlotRegion(factors = a$factor, x = a$x, y = a$y,
panel.fun = function(x, y) {
grey = c("#FFFFFF", "#CCCCCC", "#999999")
sector.index = get.cell.meta.data("sector.index")
xlim = get.cell.meta.data("xlim")
ylim = get.cell.meta.data("ylim")
circos.text(mean(xlim), mean(ylim), sector.index)
circos.points(x[1:10], y[1:10], col = "red", pch = 16, cex = 0.6)
circos.points(x[11:20], y[11:20], col = "blue", cex = 0.6)
})

# update sector
circos.updatePlotRegion(sector.index = "d", track.index = 2)
circos.points(x = -2:2, y = rep(0, 5))
xlim = get.cell.meta.data("xlim")
ylim = get.cell.meta.data("ylim")
circos.text(mean(xlim), mean(ylim), "updated")

# draw fourth track
circos.trackPlotRegion(factors = a$factor, y = a$y)
circos.trackLines(a$factor[1:100], a$x[1:100], a$y[1:100], type = "h")

# draw links
circos.link("a", 0, "b", 0, h = 0.4)
circos.link("c", c(-0.5, 0.5), "d", c(-0.5,0.5), col = "red",
border = "blue", h = 0.2)
circos.link("e", 0, "g", c(-1,1), col = "green", border = "black", lwd = 2, lty = 2)

# get info
circos.info()
circos.info(sector.index = "a", track.index = 2)

# and clear the info from memory
circos.clear()

```



```{r}

# http://stackoverflow.com/questions/31903590/r-circular-chord-plots

# ---------------
# QUESTION

library(dplyr)
library(circlize)

# Create Fake Flight Information in a table
orig = c("IE","GB","US","ES","FI","US","IE","IE","GB")
dest = c("FI","FI","ES","ES","US","US","FI","US","IE")
direc = c("IB","OB","RETURN","DOM","OB","DOM","IB","RETURN","IB")
mydf = data.frame(orig, dest, direc)

# Add a column that combines the dest and direction together
mydf <- mydf %>%
  mutate(key = paste(dest,direc)) %>%
  select (orig, key)

# Create a Binary Matrix Based on mydf
mymat <- data.matrix(as.data.frame.matrix(table(mydf)))

# create the objects you want to link from to in your diagram
from <- rownames(mymat)
to <- colnames(mymat)

# Create Diagram by suppling the matrix 
par(mar = c(1, 1, 1, 1))
chordDiagram(mymat, order = sort(union(from, to)), directional = TRUE)
circos.clear()




# --------
# ANSWER

df = data.frame(orig, dest, direc, stringsAsFactors = FALSE)
df = unique(df)
col = c("IB" = "red",
        "OB" = "blue",
        "RETURN" = "orange",
        "DOM" = "green")
directional = c("IB" = -1,
                "OB" = 1,
                "RETURN" = 2,
                "DOM" = 0)
diffHeight = c("IB" = -0.04,
                "OB" = 0.04,
                "RETURN" = 0,
                "DOM" = 0)
chordDiagram(df[1:2], col = col[df[[3]]], directional = directional[df[[3]]], 
    direction.type = c("arrows+diffHeight"),
    diffHeight = diffHeight[df[[3]]])

legend("bottomleft", pch = 15, legend = names(col), col = col)




```





```{r}

# [http://www.molecularecologist.com/2014/12/migration-routes-as-circos-plots-in-r/]

library(migest)
library(plyr)


df1 <- read.table("df1.txt", header=TRUE, stringsAsFactors=FALSE, skip=0, sep="")
names(df1) <-c("order", "rgb", "region")
df2 <- read.table("df2.txt", header=TRUE)


df1$xmin <- 0
df1$xmax <- sum(df2$m)
n <- nrow(df1)
df1 <- cbind(df1, matrix(as.numeric(unlist(strsplit(df1$rgb,","))),nrow=n,byrow=TRUE))
names(df1)[ncol(df1)-2:0] <- c("r","g","b")
df1$rcol <- rgb(df1$r,df1$g,df1$b,max=255)
df1$rcol <- rgb(df1$r,df1$g,df1$b,alpha=200,max=255)

```



```{r}

par(mar=rep(0,4))
circos.clear()
circos.par(cell.padding=c(0,0,0,0),
track.margin=c(0,0.15),start.degree=90,gap.degree=4)
circos.initialize(factors=df1$region,
xlim=cbind(df1$xmin, df1$xmax))
circos.trackPlotRegion(ylim = c(0, 1),
factors = df1$region, track.height=0.1,

panel.fun = function(x, y) {
  name = get.cell.meta.data("sector.index")
  i = get.cell.meta.data("sector.numeric.index")
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  theta = circlize(mean(xlim), 1.3)[1, 1] %% 360
  dd <- ifelse(theta < 90 || theta > 270,
  "clockwise", "reverse.clockwise")
  aa = c(1, 0.5)
  if(theta < 90 || theta > 270)  aa =c(0, 0.5)
  circos.text(x=mean(xlim), y=1.7,
  labels=name, facing = dd, cex=0.6,  adj = aa)
  circos.rect(xleft=xlim[1], ybottom=ylim[1],
  xright=xlim[2], ytop=ylim[2],
  col = df1$rcol[i], border=df1$rcol[i])
  circos.rect(xleft=xlim[1], ybottom=ylim[1],
  xright=xlim[2]-rowSums(m)[i], ytop=ylim[1]+0.3,
  col = "white", border = "white")
  circos.rect(xleft=xlim[1], ybottom=0.3,
  xright=xlim[2], ytop=0.32, col = "white",
  border = "white")
  circos.axis(labels.cex=0.6, direction =
  "outside", major.at=seq(from=0,to=floor(df1$xmax)[i],by=5),
  minor.ticks=1,
  labels.away.percentage = 0.15)})

```



```{r}

df1$sum1 <- colSums(df2$m)
df1$sum2 <- numeric(n)
for(k in 1:nrow(df2)){
i<-match(df2$orig[k],df1$region)
j<-match(df2$dest[k],df1$region)
circos.link(sector.index1=df1$region[i], point1=c(df1$sum1[i],
df1$sum1[i] + abs(df2$m[k]/1000)),
sector.index2=df1$region[j], point2=c(df1$sum2[j],
df1$sum2[j] + abs(df2$m[k]/1000)), col = df1$lcol[i])
df1$sum1[i] = df1$sum1[i] + abs(df2$m[k]/1000)
df1$sum2[j] = df1$sum2[j] + abs(df2$m[k]/1000)}



```


# -------------------------

```{r}


install.packages("circlize")
library("circlize")

circos.clear()
circos.par(gap.degree = 3)
pi= read.csv("pi.csv")
colors= c("#542D15", "#C07F4D", "#4B2078", "#C153C9", "#0A6A6C", "#1DCEC6", "#094AA5", "#0181FD", "white", "#92B966")
chordDiagram(pi, grid.col=colors, grid.border=c("white"), transparency=0.5)



```


```{r}

# https://www.r-bloggers.com/updated-circular-plots-for-directional-bilateral-migration-data/

# https://github.com/gjabel/migest/blob/master/demo/cfplot_reg2.R

# ----------------------------------------------------

# set the current directory
setwd("C:/@data/GitHub/WorkInProgress")

# load circlize package
library(circlize)

# load international migration data package
library(migest)

# read data from `migest`
df0 <- read.csv(system.file("vidwp", "reg_flow.csv", package = "migest"), stringsAsFactors=FALSE)
df1 <- read.csv(system.file("vidwp", "reg_plot.csv", package = "migest"), stringsAsFactors=FALSE)


##
##default chord diagram
##

chordDiagram(x = df0)

##
##plot parameters
##

circos.clear()
circos.par(start.degree = 90, gap.degree = 4, track.margin = c(-0.1, 0.1), points.overflow.warning = FALSE)
par(mar = rep(0, 4))

#increasing the gaps between sectors, start at 12 o'clock, ensure no gap between the chord and the sector at the begining
# subdue warning messages and have no margins in the plot

##
##chord diagram with user selected adjustments for bilateral migration flow data
##

chordDiagram(x = df0, grid.col = df1$col, transparency = 0.25,
             order = df1$region, directional = 1,
             direction.type = c("arrows", "diffHeight"), diffHeight  = -0.04,
             annotationTrack = "grid", annotationTrackHeight = c(0.05, 0.1),
             link.arr.type = "big.arrow", link.sort = TRUE, link.largest.ontop = TRUE)

# First line of arguments reads in the data (df0) and sets the colours base on the meta data (df1).
# Second line provides the order of outer sectors and indicates that chords should be directional.
# Third line indicates that the direction of the chords will be illustrated by both arrows and a difference in height. The
#  height difference is negative to make the chord shorter at the end (with the arrow head).
# Fourth line ensures the annotations outside the sectors are not plotted, but provides a track measures to later add 
#  annotatinos such as labels and axis (see below).
# Fifth line indicates the plot should use big arrows, sort the chords left to right in each sector and 
#  plots the smallest chords first.

##
##add in labels and axis
##

circos.trackPlotRegion(
  track.index = 1, 
  bg.border = NA, 
  panel.fun = function(x, y) {
    xlim = get.cell.meta.data("xlim")
    sector.index = get.cell.meta.data("sector.index")
    reg1 = df1$reg1[df1$region == sector.index]
    reg2 = df1$reg2[df1$region == sector.index]
    
    circos.text(x = mean(xlim), y = ifelse(test = nchar(reg2) == 0, yes = 5.2, no = 6.0), 
                labels = reg1, facing = "bending", cex = 1.2)
    circos.text(x = mean(xlim), y = 4.4, 
                labels = reg2, facing = "bending", cex = 1.2)
    circos.axis(h = "top", 
                major.at = seq(from = 0, to = xlim[2], by = ifelse(test = xlim[2]>10, yes = 2, no = 1)), 
                minor.ticks = 1, major.tick.percentage = 0.5,
                labels.niceFacing = FALSE)
  }
)

# First line indicates that first track (rather than any other that may have been created) will be used.
# Second line ensures no borders are plotted on the track.
# Third line adds a track.
# Fourth and fifth line collect individual track meta data from plot object.
# Sixth and seventh line collect matching name information from plot data frame (df1).
# The first circos.text adds text from (reg1) either at y = 6 (if there is a second part of the name in reg2) or 5.2.
# The second circost.text adds text (reg2).
# The circos.axis add axis with major and minor ticks, without flipping the axis labels in the bottom half.


```

