---
title: "add rows"
output: html_notebook
---

Use the {tibble} package to add a total row to a table.

```{r}

library(dplyr)
library(tibble)

library(gapminder)

```

use the {gapminder} package 

https://github.com/jennybc/gapminder


```{r}

aggregate(lifeExp ~ continent, gapminder, median)

```

the {dplyr} way:

```{r}

gapminder %>%
  group_by(continent) %>%
  summarize(avg.lifeExp = median(lifeExp))

```



```{r}

gapminder %>%
  filter(year == 2007) 

gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  tally()

gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarise(total.pop = sum(pop))
# need to specify `pop` as.numeric! the sum causes "integer overflow"
gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarise(total.pop = sum(as.numeric(pop)))


```


now add a total world population row

```{r}

# {janitor} package
gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarise(total.pop = sum(as.numeric(pop))) %>%
  janitor::adorn_totals()

# {tibble::add_row()}
gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarise(total.pop = sum(as.numeric(pop))) %>%
  add_row(continent = "World total")


# -- breaks
gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarise(total.pop = sum(as.numeric(pop))) %>%
  add_row(continent = "World total",
          total.pop = sum(total.pop))



###

world.total <- gapminder %>%
  filter(year == 2007) %>%
  summarise(world.total = sum(as.numeric(pop))) %>%
  pull(world.total)

gapminder %>%
  group_by(continent) %>%
  summarise(total.pop = sum(as.numeric(pop))) %>%
  add_row(continent = "World total",
          total.pop = world.total)


###

gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarise(total.pop = sum(as.numeric(pop))) %>%
  add_row(continent = "World total",
          total.pop = sum(total.pop))



```

