---
title: "R Notebook"
output: html_notebook
---


```{r setup}
library(tidyverse)
library(lubridate)

library(scales)
```


Transporation Security Administration

TSA checkpoint travel numbers for 2020 and 2019

https://www.tsa.gov/coronavirus/passenger-throughput


```{r}
TSA_2020_03 <- 
tibble::tribble(
                          ~Date, ~`Total Traveler Throughput`, ~`Total Traveler Throughput (1 Year Ago - Same Weekday)`,
#
                              "3/30/2020","154,080","2,360,053",
#
                    "3/29/2020",
                      "180,002",
                    "2,510,294",
                    "3/28/2020",
                      "184,027",
                    "2,172,920",
                    "3/27/2020",
                      "199,644",
                    "2,538,384",
                    "3/26/2020",
                      "203,858",
                    "2,487,162",
                    "3/25/2020",
                      "239,234",
                    "2,273,811",
                    "3/24/2020",
                      "279,018",
                    "2,151,913",
                    "3/23/2020",
                      "331,431",
                    "2,434,370",
                    "3/22/2020",
                      "454,516",
                    "2,542,643",
                    "3/21/2020",
                      "548,132",
                    "2,227,181",
                    "3/20/2020",
                      "593,167",
                    "2,559,307",
                    "3/19/2020",
                      "620,883",
                    "2,513,231",
                    "3/18/2020",
                      "779,631",
                    "2,320,885",
                    "3/17/2020",
                      "953,699",
                    "2,177,929",
                    "3/16/2020",
                    "1,257,823",
                    "2,465,709",
                    "3/15/2020",
                    "1,519,192",
                    "2,545,742",
                    "3/14/2020",
                    "1,485,553",
                    "2,274,658",
                    "3/13/2020",
                    "1,714,372",
                    "2,634,215",
                    "3/12/2020",
                    "1,788,456",
                    "2,503,924",
                    "3/11/2020",
                    "1,702,686",
                    "2,187,298",
                    "3/10/2020",
                    "1,617,220",
                    "2,122,898",
                     "3/9/2020",
                    "1,909,363",
                    "2,378,673",
                     "3/8/2020",
                    "2,119,867",
                    "2,485,430",
                     "3/7/2020",
                    "1,844,811",
                    "2,156,262",
                     "3/6/2020",
                    "2,198,517",
                    "2,543,689",
                     "3/5/2020",
                    "2,130,015",
                    "2,402,692",
                     "3/4/2020",
                    "1,877,401",
                    "2,143,619",
                     "3/3/2020",
                    "1,736,393",
                    "1,979,558",
                     "3/2/2020",
                    "2,089,641",
                    "2,257,920",
                     "3/1/2020",
                    "2,280,522",
                    "2,301,439"
  )


```


```{r}

TSA_2020_03

```



```{r}



TSA_2020_03_clean <- TSA_2020_03 %>% 
  janitor::clean_names() %>% 
  mutate(date = mdy(date)) 

# function to convert number stored as character with comma, with a number
rem_com_num <- function(varname){
    as.numeric(str_replace_all(varname, ",", ""))
} 


TSA_2020_03_clean <-
TSA_2020_03_clean %>%
  mutate(total_2020 = rem_com_num(total_traveler_throughput),
         total_2019 = rem_com_num(total_traveler_throughput_1_year_ago_same_weekday))

```


```{r}
TSA_2020_03_long <-
TSA_2020_03_clean %>% 
  select(date, total_2019, total_2020) %>% 
  pivot_longer(-date, names_to = "count_date", values_to = "TSA_count")
```



```{r}

ggplot(TSA_2020_03_long, aes(x = date, y = TSA_count, colour = count_date)) +
  geom_line() +
  theme(legend.position = "none",
       axis.title.x = element_blank()) +
  geom_text(aes(x = as_date("2020-03-25"), y = 2000000, label = "2019"), colour = "red") +
  geom_text(aes(x = as_date("2020-03-19"), y = 1000000, label = "2020"), colour = "blue") +
  labs(title = "TSA air travel checkpoint numbers, March 2020 and 2019",
       subtitle = "Same weekday comparison",
       caption = "source: www.tsa.gov/coronavirus/passenger-throughput") +
  scale_y_continuous(name="total traveler throughput", 
                     labels = comma,
                     limits = c(0, 3000000))
  

#ggsave("TSA_throughput_March.png")

```



```{r}

ggplot(TSA_2020_03_long, aes(x = date, y = TSA_count, colour = count_date)) +
  geom_point() +
  geom_smooth() +
  theme(legend.position = "none",
       axis.title.x = element_blank()) +
  geom_text(aes(x = as_date("2020-03-25"), y = 2000000, label = "2019"), colour = "red") +
  geom_text(aes(x = as_date("2020-03-19"), y = 1000000, label = "2020"), colour = "blue") +
  labs(title = "TSA air travel checkpoint numbers, month of March",
       subtitle = "Same weekday comparison",
       caption = "source: www.tsa.gov/coronavirus/passenger-throughput") +
  scale_y_continuous(name="total traveler throughput", 
                     labels = comma,
                     limits = c(0, 3000000))
  

ggsave("TSA_throughput_March.png")

```