---
title: "R Notebook"
output: html_notebook
---

```{r}
library(datapasta)

library(dplyr)
library(tibble)
```


```{r}

headings <- c("NUM", 
              "year.of.issue", 
              "title", 
              "works",
              "other artists",
              "recording.date", "recording.location",
              "label",
              "serial.number.mono", "serial.number.stereo")

```

test run, one release
```{r}

discog_table <- 
  c(
#  
  "001",
  "1956", 
  "Bach: The Goldberg Variations",
  "Goldberg Variations",
  NA,
  "June 10 - June 16, 1955", "CBS 30th Street Studio", 
  "Columbia Masterworks", 
  "ML 5060", NA)

#

cbind.data.frame(headings, discog_table)


```


test run, three releases
```{r}

discog_table <- 
  c(
#  
  "001",
  "1956", 
  "Bach: The Goldberg Variations",
  "Goldberg Variations",
  NA,
  "June 10 - June 16, 1955", "CBS 30th Street Studio", 
  "Columbia Masterworks", 
  "ML 5060", NA,
#
  "002", 
  "1956", 
  "Beethoven: Piano Sonatas Nos. 30-32",
  "Piano Sonata No. 30, Piano Sonata No. 31, Piano Sonata No. 32",
  NA,
  "June 20 - June 29, 1956", "CBS 30th Street Studio", 
  "Columbia Masterworks", 
  "ML 5130", NA,
#  
  "003",
  "1957", 
  "Bach: Concerto No. 1 in D minor, BWV 1052 & Beethoven: Concerto No. 2 in B-flat major, Op. 19",
  "Bach: Concerto No. 1 in D minor, BWV 1052, Beethoven: Piano Concerto No. 2",
  "Leonard Bernstein / Columbia Symphony Orchestra)",
  "April 9 - April 11, 1957 and April 30, 1957", "CBS 30th Street Studio", 
  "Columbia Masterworks", 
  "ML 5211", NA)

cbind.data.frame(headings, discog_table)


```


full list of releases
```{r}
discog_table <- 
  c(
#  
  "001",
  "1956", 
  "Bach: The Goldberg Variations",
  "Goldberg Variations",
  NA,
  "June 10 - June 16, 1955", "CBS 30th Street Studio", 
  "Columbia Masterworks", 
  "ML 5060", NA,
#
  "002", 
  "1956", 
  "Beethoven: Piano Sonatas Nos. 30-32",
  "Piano Sonata No. 30, Piano Sonata No. 31, Piano Sonata No. 32",
  NA,
  "June 20 - June 29, 1956", "CBS 30th Street Studio", 
  "Columbia Masterworks", 
  "ML 5130", NA,
#  
  "003",
  "1957", 
  "Bach: Concerto No. 1 in D minor, BWV 1052 & Beethoven: Concerto No. 2 in B-flat major, Op. 19",
  "Bach: Concerto No. 1 in D minor, BWV 1052, Beethoven: Piano Concerto No. 2",
  "Leonard Bernstein / Columbia Symphony Orchestra)",
  "April 9 - April 11, 1957 and April 30, 1957", "CBS 30th Street Studio", 
  "Columbia Masterworks", 
  "ML 5211", NA,
#  
  "004",
  "1957", 
  "Bach: Partitas Nos. 5 & 6; Fugues in F-sharp minor and E major",
  "Partita No. 5 in G major, BWV 829, 
  Partita No. 6 in E minor, BWV 830,
  Fugue No. 9 in E major, BWV 878,
  Fugue No. 14 in F-sharp minor, BWV 883",
  NA,
  NA,
  "Columbia Masterworks", 
  "ML 5186", NA,
#
  "1958", "Haydn: Sonata No. 3 in E-flat major; Mozart: Sonata No. 10 in C major, K.330; Fantasia and Fugue in C major, K.394",
  "Haydn: Piano Sonata No. 59",
  "Mozart: Piano Sonata No. 10",
  "Mozart: Fantasia and Fugue",
  "Columbia Masterworks, ML 5274",
#
  "1958", "Beethoven: Concerto No. 1 in C major; Bach: Concerto No. 5 in F minor",
  "Bach: Keyboard concerto No. 5",
  "Beethoven: Piano Concerto No. 1",
  "(with Vladimir Golschmann / Columbia Symphony Orchestra)",
  NA,
  "Columbia Masterworks, ML 5298, MS 6017",
#
  "1959", "tBerg: Sonata for Piano, Op. 1; Schoenberg: Three Piano Pieces, Op. 11; Krenek: Sonata No. 3 for Piano, Op. 92, No. 4",
  "Berg: Piano Sonata, Op. 1",
  "Schoenberg: Three Piano Pieces, Op. 11",
  "Krenek: Piano Sonata No. 3, Op. 92, No. 4",
  "Columbia Masterworks, ML 5336",
#
  "1960", "Gould: String Quartet No. 1",
  "String Quartet in F minor, Op. 1",
  "(performed by Symphonia Quartet)",
  NA,
  "Columbia Masterworks, ML 5578, MS 6178",
#
  "1960", "Beethoven: Piano Concerto No. 3 in C minor, Op. 37",
  "Piano Concerto No. 3",
  "(with Leonard Bernstein / Columbia Symphony Orchestra)",
  NA,
  "Columbia Masterworks, ML 5418, MS 6096",
#
  "1960", "Bach: Italian Concerto in F major & Partita Nos. 1 & 2",
  "Italian Concerto, BWV 971",
  "Partita No. 1 in B-flat major, BWV 825",
  "Partita No. 2 in C minor, BWV 826",
  "Columbia Masterworks, ML 5472, MS 6141",
#
  "1961", "Brahms: 10 Intermezzi",
  "Intermezzo in A major, Op. 76, No. 6",
  "Intermezzo in A minor, Op. 76, No. 7",
  "Intermezzo in E major, Op. 116, No. 4",
  "Intermezzo in E-flat major, Op. 117, No. 1",
  "Intermezzo in B-flat minor, Op. 117, No. 2",
  "Intermezzo in C-sharp minor, Op. 117, No. 3",
  "Intermezzo in A minor, Op. 118, No. 1",
  "Intermezzo in A major, Op. 118, No. 2",
  "Intermezzo in E-flat minor, Op. 118, No. 6",
  "Intermezzo in B minor, Op. 119, No. 1",
  "Columbia Masterworks, ML 5637, MS 6237",
#
  "1961", "Beethoven: Piano Concerto No. 4 in G major, Op. 58",
  "Piano Concerto No. 4",
  "(with Leonard Bernstein / New York Philharmonic)",
  NA,
  "Columbia Masterworks, ML 5662, MS 6262",
#
  "1962", "Mozart: Piano Concerto No. 24 in C minor, K. 491 & Schoenberg: Piano Concerto, Op. 42",
  "Mozart: Piano Concerto No. 24 (with Walter Susskind / CBC Symphony Orchestra)",
  "Schoenberg: Piano Concerto (with Robert Craft / CBC Symphony Orchestra)",
  "Columbia Masterworks, ML 5739, MS 6339",
#
  "1962", "Bach: The Art of the Fugue, Volume I",
  "The Art of Fugue, Fugues 1 - 9",
  "(played on organ)",
  NA,
  "Columbia Masterworks, ML 5738, MS 6338",
#
  "1962", "Strauss: Enoch Arden (Tennyson), Op. 38",
  "Enoch Arden",
  "(with Claude Rains, speaker)",
  NA,
  "Columbia Masterworks, ML 5741, MS 6341",
#
  "1963", "Bach: The Well-Tempered Clavier, Book I Volume I, BWV 846-853",
  "The Well-Tempered Clavier, Book I, Preludes and Fugues 1 - 8",
  "Columbia Masterworks, ML 5739, MS 6339",
#
  "1963", "Bach: Partitas 3 & 4, Toccata 7",
  "Partita No. 3 in A minor, BWV 827",
  "Partita No. 4 in D major, BWV 828",
  "Toccata No. 7 in E minor",
  "Columbia Masterworks, ML 5898, MS 6498",
#
  "1963", "Bach: The Well-Tempered Clavier, Book I Volume 2, BWV 854-861",
  "The Well-Tempered Clavier, Book I, Preludes and Fugues 9 - 16",
  "Columbia Masterworks, ML 5938, MS 6538",
#
  "1964", "Bach: Two and Three Part Inventions, BWV 772-801 (Inventions & Sinfonias)",
  "Inventions and Sinfonias, BWV 772-801",
  "March 18 & 19, 1964 in CBS 30th Street Studio", "Columbia Masterworks, ML 6022, MS 6622",
#
  "1965", "Beethoven: Sonatas No. 5-7, Op. 10, No. 1-3",
  "Piano Sonata No. 5",
  "Piano Sonata No. 6",
  "Piano Sonata No. 7",
  "Columbia Masterworks, ML 6086, MS 6686",
#
  "1965", "Bach: The Well-Tempered Clavier, Book I Volume 3, BWV 862-869",
  "The Well-Tempered Clavier, Book I, Preludes and Fugues 17 - 24",
  "Columbia Masterworks, ML 6176, MS 6776",
#
  "1966", "The Music of Arnold Schoenberg, Vol. IV",
  "2 Ges?nge for baritone, Op. 1 (with Donald Gramm, bass-baritone)",
  "Vier Lieder, Op. 2 (with Ellen Faull, soprano)",
  "Drei Klavierst?cke, Op. 11 (originally released in 1959 on ML 5336)",
  "Das Buch der h?ngenden G?rten, Op. 15 (with Helen Vanni, mezzo-soprano)",
  "Sechs kleine Klavierst?cke, Op. 19",
  "5 St?cke for Piano, Op. 23",
  "Suite for Piano, Op. 25",
  "Zwei Klavierst?cke, Op. 33",
  "Columbia Masterworks, M2L 336",
#
  "1966", "Beethoven: Piano Concerto No. 5 in E-flat major, Op. 73, \"Emperor\"",
  "Piano Concerto No. 5",
  "(with Leopold Stokowski / American Symphony Orchestra)",
  NA,
  "Columbia Masterworks, ML 6288, MS 6888",
#
  "1967", "Beethoven: Sonatas for Piano No. 8-10, Op. 13 \"Path?tique\", Op. 14, No. 1 & 2",
  "Piano Sonata No. 8",
  "Piano Sonata No. 9",
  "Piano Sonata No. 10",
  "Columbia Masterworks, ML 6345, MS 6945",
#
  "1967", "Bach: Three Keyboard Concertos, BWV 1054, 1056 & 1058",
  "Concerto for harpsichord and strings in D major, BWV 1054",
  "Concerto for harpsichord and strings in F minor, BWV 1056 (originally released in 1967 on ML 5298/MS 6017)",
  "Concerto for harpsichord and strings in G minor, BWV 1058",
  "(with Vladimir Golschmann / Columbia Symphony Orchestra)",
  NA,
  "Columbia Masterworks, ML 6401",
#
  "1967", "Canadian Music in the XXth Century",
  "Morawetz: Fantasy in D minor",
  "Anhalt: Fantasia",
  "H?tu: Variations",
  "CBS Masterworks, 32 11 0045/32 11 0046",
#
  "1967", "The Music of Arnold Schoenberg, Vol. VII",
  "Trio for Violin, Viola and Cello, Opus 45 (performed by members of the Juilliard Quartet)",
  "Ode to Napoleon Buoanaparte, Opus 41 (with Juilliard String Quartet/John Horton, speaker)",
  "Variations on a Recitative, Opus 40 (performed by Marilyn Mason, organ)",
  "Fantasy for Violin and Piano, Opus 47 (with Israel Baker, violin)",
  "Theme and Variations, Opus 43B (performed by Eugene Ormandy/Philadelphia Orchestra)",
  "Columbia Masterworks, M2L 367",
#
  "1968", "Beethoven: Symphony No. 5 in C minor, Op. 67 (Transcribed for Piano by Franz Liszt)",
  "Beethoven / Liszt: Symphony No. 5",
  "Columbia Masterworks, MS 7095",
#
  "1968", "Bach: The Goldberg Variations", "June 10 - June 16, 1955 in CBS 30th Street Studio, rechanneled for stereo 1968", "Columbia Masterworks, MS 7096",
#
  "1968", "The Mozart Piano Sonatas, Vol. 1",
  "Piano Sonata No. 1",
  "Piano Sonata No. 2",
  "Piano Sonata No. 3",
  "Piano Sonata No. 4",
  "Piano Sonata No. 5",
  "Columbia Masterworks, MS 7097",
#
  "1968", "Bach: The Well-Tempered Clavier, Book II Volume I, BWV 870-877",
  "The Well-Tempered Clavier, Book II, Preludes and Fugues 1 - 8",
  "August 8, 1966; January 24, 1967; February 20, 1967 in CBS 30th Street Studio", "Columbia Masterworks, MS 7099",
#
  "1968", "Glenn Gould: Concert Dropouts - In Conversation with John McClure",
  "The Concert Is Dead",
  "The Only Excuse For Recording Is To Do It Differently",
  "The Great Get-Sibelius Plot Exposed",
  "A Live Audience Is A Great Liability",
  "Petula Clark's Songs Are In The Post-Mendelssohn Tradition",
  "Why I Sing Along",
  "Electronic Music Is The Future",
  "(John McClure, interviewer)",
  NA,
  "Columbia Masterworks, BS 15 (bonus disc released with MS 7095)",
#
  "1969", "Scriabin: Sonata No. 3 in F-sharp minor, Op. 23 & Prokofiev: Sonata No. 7 in B-flat major, Op. 83",
  "Scriabin: Piano Sonata No. 3",
  "Prokofiev: Piano Sonata No. 7",
  "Columbia Masterworks, MS 7173",
#
  "1969", "The Mozart Piano Sonatas, Vol. 2",
  "Piano Sonata No. 6",
  "Piano Sonata No. 7",
  "Piano Sonata No. 9",
  "Columbia Masterworks, MS 7274",
#
  "1969", "Bach: Keyboard Concertos, Vol. II",
  "Concerto for harpsichord and strings in E major, BWV 1053",
  "Concerto for harpsichord and strings in A major, BWV 1055",
  "(with Vladimir Golschmann / Columbia Symphony Orchestra)",
  NA,
  "Columbia Masterworks, MS 7294",
#
  "1969", "Schumann: Piano Quintet in E Flat; Piano Quartet in E Flat; The Three String Quartets",
  "Quartet in A Minor, Op. 41, No. 1 (performed by Juilliard String Quartet)",
  "Quartet in F Major, Op. 41, No. 2 (performed by Juilliard String Quartet)",
  "Quartet in A Major, Op. 41, No. 3 (Performed by Juilliard String Quartet)",
  "Quintet for Piano and Strings in Eb Major, Op. 44 (performed by Leonard Bernstein, piano/Juilliard String Quartet)",
  "Quartet for Piano and Strings in Eb Major, Op. 47 (with members of the Juilliard String Quartet)",
  "Columbia Masterworks, D3S 806",
#
  "1970", "Bach: The Well-Tempered Clavier, Book II Volume II, BWV 878-885",
  "The Well-Tempered Clavier, Book II, Preludes and Fugues 9 - 16",
  "Columbia Masterworks, MS 7409",
#
  "1970", "Glenn Gould Plays Beethoven Sonatas Nos. 8, 14 & 23",
  "Piano Sonata No. 8",
  "Piano Sonata No. 14",
  "Piano Sonata No. 23",
  "Columbia Masterworks, MS 7413",
#
  "1970", "Beethoven: Variations for Piano",
  "32 Variations in C minor",
  "Six variations on a theme in F major, Op. 34",
  "Eroica Variations",
  "Columbia Masterworks, M 30080",
#
  "1971", "Bach: The Well-Tempered Clavier, Book II Volume III, BWV 886-893",
  "The Well-Tempered Clavier, Book II, Preludes and Fugues 17 - 24",
  "Columbia Masterworks, MS 30537",
#
  "1971", "A Consort of Musicke bye William Byrde and Orlando Gibbons",
  "Byrd: The Firste Pavian; The Galliarde to the Firste Pavian; Pavana the Sixte Kinbrugh Goodd; The Galliarde to the Sixte Pavian; Hughe Ashtons Grownde: A Voluntarie; Sellingers Rownde",
  "Gibbons: \"Lord Of Salisbury\" Pavan And Galliard; Allemande (Italian Ground); Fantasy in C major",
  "Columbia Masterworks, M 30825",
#
  "1972", "The Mozart Piano Sonatas, Vol. 3",
  "Piano Sonata No. 8",
  "Piano Sonata No. 10",
  "Piano Sonata No. 12",
  "Piano Sonata No. 13",
  "Columbia Masterworks, M 31073",
#
  "1972", "Schoenberg: Complete Songs for Voice and Piano, Vol. 1",
  "2 Ges?nge for baritone, Op. 1 (with Donald Gramm, bass-baritone)",
  "Vier Lieder, Op. 2 (with Ellen Faull, soprano)",
  "Das Buch der h?ngenden G?rten, Op. 15 (with Helen Vanni, mezzo-soprano)",
  "(all tracks previously released on M2S 736, 1966)",
  NA,
  "Columbia Masterworks, M 31311",
#
  "1972", "Schoenberg: Complete Songs for Voice and Piano, Vol. 2",
  "Six Songs, Op. 3",
  "Eight Songs, Op. 6",
  "Two Ballads, Op. 12",
  "Two Songs, Op. 14",
  "Three Songs, Op. 48",
  "Two Songs, Op. posth.",
  "(with Donald Gramm, bass-baritone; Cornelius Opthof, baritone and Helen Vanni, mezzo-soprano)",
  NA,
  "Columbia Masterworks, M 31312",
#
  "1972", "Music from Kurt Vonnegut's Slaughterhouse-Five",
  "Keyboard concerto No. 5",
  "Variations 18 & 25 from The Goldberg Variations",
  "Brandenburg Concerto No. 4 in G major, BWV 1049",
  "Concerto for harpsichord and strings in D major, BWV 1054",
  "Fantasia super: Komm, Heiliger Geist, Herre Gott, BWV 651",
  "(OST Slaughterhouse-Five, all tracks previously released)",
  NA,
  "Columbia Masterworks, S 31333",
#
  "1972", "H?ndel: Suites for the Harpsichord",
  "Suite No. 1 in A major, HWV 426",
  "Suite No. 2 in F major, HWV 427",
  "Suite No. 3 in D minor, HWV 428",
  "Suite No. 4 in E minor, HWV 429",
  "(performed on harpsichord)",
  NA,
  "Columbia Masterworks, M 31512",
#
  "1973", "Glenn Gould's First Recordings of Grieg and Bizet",
  "Grieg: Piano Sonata",
  "Bizet: Premier Nocturne; Variations Chromatiques",
  "Columbia Masterworks, M 32040",
#
  "1973", "Bach: The French Suites, Vol. 1",
  "Suite No. 1 in D minor, BWV 812",
  "Suite No. 2 in C minor, BWV 813",
  "Suite No. 3 in B minor, BWV 814",
  "Suite No. 4 in E-flat major, BWV 815",
  "Columbia Masterworks, M 32347",
#
  "1973", "The Mozart Piano Sonatas, Vol. 4",
  "Piano Sonata No. 11",
  "Piano Sonata No. 15",
  "Piano Sonata No. 16",
  "Fantasia in D minor, K. 397",
  "Columbia Masterworks, M 32348",
#
  "1973", "Beethoven: Piano Sonatas, Op. 31 Complete",
  "Piano Sonata No. 16",
  "Piano Sonata No. 17",
  "Piano Sonata No. 18",
  "Columbia Masterworks, M 32349",
#
  "1973", "Glenn Gould Plays Hindemith's Piano Sonatas 1-3",
  "Piano Sonata No. 1",
  "Piano Sonata No. 2",
  "Piano Sonata No. 3",
  "CBSa Masterworks, M 32350",
#
  "1973", "Glenn Gould Plays His Own Transcriptions of Wagner Orchestral Showpieces",
  "Prelude to Act I (from Die Meistersinger)",
  "\"Dawn\" and \"Siegfried's Rhine Journey\" (from G?tterd?mmerung)",
  "Siegfried Idyll",
  "1973, Eaton Auditorium, Toronto", "CBS Masterworks, M 32351",
#
  "1974", "Bach: The French Suites, Vol. 2 & Overture in the French Style",
  "French Suite No. 5 in G major, BWV 816",
  "French Suite No. 6 in E major, BWV 817",
  "Overture in the French style, BWV 831",
  "CBS Masterworks, M 32853",
#
  "1974", "Bach: The Three Sonatas for Viola da Gamba & Harpsichord",
  "Sonata No. 1 in G major, BWV 1027",
  "Sonata No. 2 in D major, BWV 1028",
  "Sonata No. 3 in G minor, BWV 1029",
  "(with Leonard Rose, cello)",
  NA,
  "CBS Masterworks, M 32934",
#
  "1975", "Beethoven: Bagatelles, Op. 33 & Op. 126",
  "Bagatelles, Op. 33",
  "Bagatelles, Op. 126",
  "CBS Masterworks, M 33265",
#
  "1975", "The Mozart Piano Sonatas, Vol. 5",
  "Fantasia in C Minor, K. 475",
  "Piano Sonata No. 14 in C minor, K. 457",
  "Piano Sonata No. 17 in B-flat major, K. 570",
  "Piano Sonata No. 18 in D major, K. 576",
  "June 23, 1974; November 9, 1974; & September 7, 1974 in Columbia 30th Street Studio, New York", "Columbia Masterworks, M 33515",
#
  "1976", "Hindemith: The Complete Sonatas For Brass & Piano",
  "Sonata in F for French Horn and Piano",
  "Sonata for Bass Tuba and Piano",
  "Sonata for Trumpet and Piano",
  "Sonata in E-flat for Alto Horn and Piano",
  "Sonata for Trombone and Piano",
  "(with members of the Philadelphia Brass Ensemble)",
  NA,
  "CBS Masterworks, M2 33971",
#
  "1976", "Bach: The Six Sonatas for Violin and Harpsichord",
  "Sonata in B minor for violin and harpsichord, BWV 1014",
  "Sonata in A major for violin and harpsichord, BWV 1015",
  "Sonata in E major for violin and harpsichord, BWV 1016",
  "Sonata in C minor for violin and harpsichord, BWV 1017",
  "Sonata in F minor for violin and harpsichord, BWV 1018",
  "Sonata in G major for violin and harpsichord, BWV 1019",
  "(with Jaime Laredo, violin)",
  NA,
  "CBS Masterworks, M2 34226",
#
  "1977", "Glenn Gould Plays Sibelius",
  "Sonatine No. 1 for Piano in E major, Op. 67",
  "Sonatine No. 2 for Piano in E major, Op. 67",
  "Sonatine No. 3 for Piano in B minor, Op. 67",
  "Kyllikki, Op. 41",
  "CBS Masterworks, M 34555",
#
  "1977", "Glenn Gould Plays Bach: The English Suites Complete",
  "Suite No. 1 in A Major, BWV 806",
  "Suite No. 2 in A Minor, BWV 807",
  "Suite No. 3 in G Minor, BWV 808",
  "Suite No. 4 in F Major, BWV 809",
  "Suite No. 5 in E Minor, BWV 810",
  "Suite No. 6 in D Minor, BWV 811",
  "BWV 806: March 11 & November 4, 1973",
  "BWV 807: May 23, 1971",
  "BWV 808: June 21 & 22, 1974",
  "BWV 809 and BWV 810: December 14 & 15, 1974 and May 23 & 24, 1976",
  "BWV 811: October 10 & 11, 1975 and May 23 & 24, 1976",
  "Eaton's Auditorium",
  NA,
  "CBS Masterworks, M2 34578",
#
  "1978", "Hindemith: Das Marienleben for Soprano & Piano",
  "Das Marienleben",
  "(with Roxolana Roslak, soprano)",
  NA,
  "CBS Masterworks, M2 34597",
#
  "1979", "Bach: The Toccatas, Vol. 1",
  "Toccata in F-sharp minor, BWV 910",
  "Toccata in D major, BWV 912",
  "Toccata in D minor, BWV 913",
  "CBS Masterworks, M 35144",
#
  "1980", "Bach: The Toccatas, Vol. 2",
  "Toccata in C minor, BWV 911",
  "Toccata in E minor, BWV 914",
  "Toccata in G minor, BWV 915",
  "Toccata in G major, BWV 916",
  "CBS Masterworks, M 35831",
#
  "1980", "Bach: Prelude, Fughettas & Fugues",
  "Prelude And Fugue in A minor, BWV 895",
  "Prelude And Fughetta in D minor, BWV 899",
  "Prelude And Fugue in E minor, BWV 900",
  "Preludes, BWV 902 & 902A",
  "Fughetta in G major, BWV 902",
  "Prelude in C major, BWV 924",
  "Prelude in D major, BWV 925",
  "Prelude in D minor, BWV 926",
  "Prelude in F major, BWV 927",
  "Prelude in F major, BWV 928",
  "Prelude in G minor, BWV 930",
  "Prelude in C major, BWV 933",
  "Prelude in C minor, BWV 934",
  "Prelude in D minor, BWV 935",
  "Prelude in D major, BWV 936",
  "Prelude in E major, BWV 937",
  "Prelude in E minor, BWV 938",
  "Fugue in C major, BWV 952",
  "Fugue in C major, BWV 953",
  "Fughetta in C minor, BWV 961",
  "CBS Masterworks, M 35891",
#
  "1980", "Beethoven: Piano Sonatas, Op. 2, Nos. 1-3, Op. 28, \"Pastoral\"",
  "Piano Sonata No. 1",
  "Piano Sonata No. 2",
  "Piano Sonata No. 3",
  "Piano Sonata No. 15",
  "CBS Masterworks, M2 35911",
#
  "1981", "The Glenn Gould Silver Jubilee Album",
  "Scarlatti: Sonatas, L 463, 413, and 486",
  "C.P.E. Bach: W?rttemberg Sonata No. 1",
  "Gould: So You Want to Write A Fugue? (performed by Elizabeth Benson-Guy, soprano/Anita Darian, contralto/Charles Bressler, tenor/Donald Gramm, baritone/Juilliard String Quartet/Vladimir Golschmann, conductor)",
  "Scriabin: Two Pieces, Op. 57",
  "Strauss: Ophelia-Lieder (with Elisabeth Schwarzkopf, soprano)",
  "Beethoven-Liszt: Pastoral Symphony, First Movement",
  "A Glenn Gould Fantasy (with Margaret Pacsu)",
  "CBS Masterworks M2X 35914",
#
  "1982", "Haydn: The Six Last Sonatas",
  "Piano Sonata No. 56, Hob. XVI/No. 42",
  "Piano Sonata No. 58, Hob. XVI/No. 48",
  "Piano Sonata No. 59, Hob. XVI/No. 49",
  "Piano Sonata No. 60, Hob. XVI/No. 50",
  "Piano Sonata No. 61, Hob. XVI/No. 51",
  "Piano Sonata No. 62, Hob. XVI/No. 52",
  "CBS Masterworks, I2M 36947",
#
  "1982", "Bach: The Goldberg Variations (1981 Digital Recording)",
  "Goldberg Variations",
  "CBS Masterworks, IM 37779",
#
  "1982", "Glenn Gould Discusses His Performances of the \"Goldberg Variations\" with Tim Page", "", "CBS Masterworks, CDN-70 (Bonus disc released with IM 37779)",
#
  "1982", "A State of Wonder: The Complete Goldberg Variations, 1955 & 1981", "* 3 discs: 1955 and 1981 recordings plus 1955 outtakes and Gould's final radio interview", "Sony Classical, S3K 87703",
#
  "1983", "Brahms: Ballades, Op. 10 & Rhapsodies, Op. 79",
  "Ballades, Op. 10",
  "Rhapsodies, Op. 79",
  "February 8,9 & 10 1982 in RCA's Studio A in New York (Ballades)",
  "June 30,& July 1 1982 in RCA's Studio A in New York (Rhapsodies)",
  "CBS Masterworks, IM 37800",
#
  "1983", "Beethoven: Sonatas No. 12, Op. 26 & No. 13, Op. 27, No. 1",
  "Piano Sonata No. 12",
  "Piano Sonata No. 13",
  "CBS Masterworks, M 37831",
#
  "1984", "Richard Strauss: Sonata, Op. 5; 5 Piano Pieces, Op. 3",
  "Five Piano Pieces, Op. 3",
  "Piano Sonata in B minor, Op. 5",
  "September 1-3, 1982 in RCA's Studio A in New York (Sonata op.5)",
  "April 23 & 6 August 6, 1979 in Old St.Laurence Hall in Toronto (Piano Pieces 1-4); September 5, 1979 in Eaton's Auditorium in Toronto (Piano Piece 5)",
  "CBS Masterworks, IM 38659",
#
  "1990", "Glenn Gould Conducts & Plays Wagner",
  "Siegfried Idyll * (original version for 13 instruments): Glenn Gould, conductor",
  "Prelude to Act I (from Die Meistersinger) **",
  "\"Dawn\" and \"Siegfried's Rhine Journey\" (from G?tterd?mmerung) **",
  "Siegfried Idyll **",
  "* July 27-29 & September 8, 1982, St. Lawrence Hall, Toronto / ** 1973, Eaton Auditorium, Toronto (originally released in 1973 by Columbia Masterworks, M 32351)", "Sony Classical, SK 46279",
  "References")

vector_paste_vertical()

```



